backupwordpress.php
"Noticed the following error on the hmn.md network:
```
E_WARNING: fopen(s3:/***/*****-production/uploads/sites/5/backupwordpress-*******-backups/.schedule-default-1-running): failed to open stream: No such file or directory
```
The error is caused because a scheduled backup is trying to run even though the backups directory doesn't exist / isn't writable.
However the backup scheduled shouldn't be running in this situation, we have a function `hmbkp_possible()` which checks for such a thing and if those checks fail we disable the backups page completely and show a warning message. It looks like we missed also disabling scheduled backups
=> Scheduled backups shouldn't run if backups are not possible

classes/wp-cli.php
wp-cli also has a path argument to point to a wordpress installtion.
Hence using the path argument with backupwordpress interfers with
the global one and the wp installation won't be found anymore.
Renaming the argument to backup_path is probably the sanest option.
=> path argument interfers with wp-cli path argument.

classes/class-hmbkp-path.php
```
Parse error: syntax error, unexpected T_STATIC, expecting T_STRING or T_VARIABLE or '$' in /home4/crossq/public_html/edsung/wp-content/plugins/backupwordpress/classes/class-hmbkp-path.php on line 74
````
=> User reported update error

classes/class-schedule.php
This is so we can handle any unexpected cases with the default case
=> Add all cases to switch

classes/class-schedule.php
Fixes
https://github.com/humanmade/backupwordpress/issues/672
https://github.com/humanmade/backupwordpress/issues/673
=> Pass scanned files sizes through conform_dir()

backupwordpress.php, classes/class-service.php, functions/core.php
Fixes a bug with the Service settings that were not being saved because of the backslashes in the settings key names.
Also migrates any existing settings to the new naming convention. If multiple version of settings names are present in the DB, then only one will be kept.
For example, an existing site with the Google Drive addon could have 2 different serialized schedule settings for services:
`HMBKP_GDV_Backup_Service`
`HM\BackUpWordPressGDrive\Google_Drive_BackUp`
The new setting name will be `google-drive`
The upgrade routine will loop over these two and whichever one is the last to be iterated over will carry its values over to the new setting.
=> Fixes settings not saving

admin/actions.php, admin/schedule-form.php, admin/schedule-settings.php
Had a few reports of the email notification settings field not saving the email address entered.
https://app.intercom.io/a/apps/7f1l4qyq/inbox/all/conversations/721264065
https://app.intercom.io/a/apps/7f1l4qyq/inbox/all/conversations/720633313
***How to test***
Activate BWP and an addon.
Try entering an invalid email address in the email notification field. Should reload and display an error notice.
Entering a valid email should clear notice.
Enter the settings for an addon - but omit one of the fields. Should reload and display a notice that the field is required
Fill in correct info and notice should be cleared.
=> Email settings field may not be saving

admin/schedule-form-excludes.php, backupwordpress.php, classes/class-backup.php, classes/class-schedule.php, classes/class-setup.php, composer.json, composer.lock
***Original issue***
There's also a managewp folder we can exclude. Additionally, I don't know what plugin it originated from but I saw a ```backups-*****``` folder, maybe we can catch that too.
***PR Summary***
I took a bit of a deep dive into how we were calculating directory sizes and scanning the filesystem.
I tried to consolidate our different scanning functions to use the Symfony Finder component which provides a layer of abstraction on top of the SPL Iterators.
It will allow us to do more complex "queries" in the future. It also irons out a few bugs in the default PHP Iterators and deals with cross platform inconsistencies. It's compatible with PHP 5.3
Whenever you see a directory size now, it has been calculated without the default excluded folders, for example any `.git` folder …
=> Exclude Envato-backups folders by default

classes/class-backup.php, classes/class-schedule.php, classes/class-setup.php, functions/core.php
This fixes a bug where we were trying to use `conform_dir` on an SPL object instead of on a path string.
=> Fix incorrect type error

admin/schedule-form.php, admin/schedule-sentence.php, functions/interface.php
We should adda description and placeholders telling the user that they need to use 24H format, and display the time as such in the sentence.
=> Schedule time format is inconsistent

backupwordpress.php
Plugins are ranked by exact search term match. So if you search for backup or backups, the first results will be plugins with "backup or "backups" as a word in them
Not sure if we need to rebrand or just change the name:
Not sure if we can use `BackUp WordPress`, so maybe  `BackUpWordPress Backup Plugin`, other plugin authors are already using the trick.
@willmot @noeltock @owaincuvelier thoughts?
=> Change plugn name to include backup as a keyword

classes/class-backup.php, tests/other/testBackupPath.php
The `user_can_connect` method was wrongly coded. It established a connection but then didn't quit so it made it impossible to execute any other commands.
This PR fixes that by adding the `--execute` option with a value of `quit` to quit the mysql command prompt immediately.
Also it makes the `FS` option a user defined constant because it was causing too many issues.
It also adds some user defined constants for forcing the zip method. Useful for debugging.
=> Fixes the zip method backup

admin/actions.php
If a user selects "once monthly" and removes the value from the "day of month" field then switches to a schedule that does not use that field, and submits the form, it causes a form validation error.
we should not validate a field value if it will not be used, maybe we can do it with JS on the dropdown event, we can set a default value
=> Settings validation logic error

classes/class-backup.php
Fixes the warning if `shell_exec()` is not enabled
=> Check if shell_exec is available first

backupwordpress.php, classes/class-backup.php, classes/class-plugin.php, package.json, readme.txt, readme/readme-footer.txt, readme/readme-header.txt, tests/backup/testFullBackupTest.php
When I refactored the plugin in 3.2.0 , I made it so `get_files` would just skip default excludes completely. However, `get_files` is used in `get_included_files` which is used by the full backup unit tests functions to test if the resulting zip archive contains the same number of folders and files as there actually should be.
As the full backup tests don't run anymore on Travis - they are completely excluded, I didn't notice that some default exclude patterns were too greedy. This led to some core files being excluded. Including some BackUpWordPress files ( `backups.php` and `backup-table.php` )
Should we revert to running full backup tests on Travis?
=> Fixes full backup tests

classes/class-backup.php
I'm trying to run this on a multisite with WP in a subdirectory. This is only possible if I can define the HMBKP_ROOT - as this is incorrectly calculated otherwise.
However `get_home_path` doesn't use the defined value. If this is added here - it all works fine.
=> Get home path should return defined value

classes/class-backup.php
I had wrongly removed an exclude pattern causing the total size to be miscalculated
=> Exclude backups folder from size calculation

admin/schedule-form.php, classes/class-plugin.php, functions/interface.php
I'm not sure why, but the multisite `get_current_screen` returns `settings_backupwordpress-network` not `settings_backupwordpress`
=> Fixes admin page slug for multisite

classes/class-backupwordpress-wp-cli-command.php
Fixes two errors when trying to run `wp backupwordpress backup`
```
PHP Fatal error:  Class 'Backup' not found in wp-content/plugins/backupwordpress/classes/class-backupwordpress-wp-cli-command.php on line 57
PHP Fatal error:  Class 'Path' not found in wp-content/plugins/backupwordpress/classes/class-backupwordpress-wp-cli-command.php on line 63
```
=> Use namespaced functions

classes/class-schedule.php
`Warning: array_key_exists() [function.array-key-exists]: The first argument should be either a string or an integer in /home/content/52/9722152/html/wp-content/plugins/backupwordpress/classes/class-schedule.php on line 416`
=> Error if variable is wrong type

.travis.yml
Currently Travis is only testing up to PHP 5.5, given 5.6 is now the stable release, we should start testing under it too.
=> Test under PHP 5.6 in Travis

classes/class-backup.php
Fixes https://github.com/humanmade/backupwordpress/issues/694
=> Catch database and files shell_exec warnings

CONTRIBUTING.md
Add a section on security to the contributing.md file. Fixes https://github.com/humanmade/backupwordpress/pull/840
=> explain how contributors should report security issues

admin/actions.php
Fixes #821 
We could also add more details to our support centre, as we link to it:
Causes can be maintenance mode plugins. htaccess protection... there are workarounds that would be worth mentioning, see BackUpBuddy docs for example
http://ithemes.com/codex/page/BackupBuddy:_Frequent_Support_Issues#HTTP_Loopback_Connections_Disabled
=> Changed wording for wp-cron error

admin/schedule-form-excludes.php
Currently if you browse into an empty folder via the site list table the whole table disappears. A common example of an empty folder is `\wp-content\upgrade`. Here's what that looks like on current master:
This PR introduces proper handling, the table shows up with a short sentence letting the user know the directory is empty.
=> Properly handle empty directories in file listing

classes/class-path.php
Fixes the unit test errors reported in https://github.com/humanmade/backupwordpress/pull/869#issuecomment-144707430
See https://core.trac.wordpress.org/ticket/31767 for discussion on the Core change we caused this to be an issue.
=> Ensure we create the `.htaccess` file instead of relying on `insert_with_markers` to create it

admin/schedule-sentence.php, classes/class-schedule.php
And it should be, this was broken at some point. I think in https://github.com/humanmade/backupwordpress/pull/743
I found two issues.
- We were no longer passing the `$skip_excluded_files` argument all the way through to `filesize`. Fixed that in https://github.com/humanmade/backupwordpress/commit/16d0ddfb8485e2a3dc0a59bc6d34f172078bb526
- https://github.com/humanmade/backupwordpress/commit/d8ba9e4f15ccfdc480b03ee51cc2fbf16966a6e8 shortcuts filesize so it doesn't ever get to the exclude ignoring code if it's passed the route directoy. @pdewouters any idea why that was added?
=> Site size isn't ignoring excluded files

functions/interface.php, grunt/aliases.yml
Fixes https://github.com/humanmade/backupwordpress/issues/855
- Makes notices dismissable.
- The release alias copies the plugin files to a release folder and zips it ready for upload to Github. The release folder can act as the svn checkout dir.
=> Fix duplicate notices

classes/class-backup.php
When the `zip` method was used, it would then evaluate the next conditional and always evaluate the condition that displays the `no valid archive method found`
=> Fix false positive error message

admin/schedule-form-excludes.php, classes/class-schedule.php
Don't special case pre-calculate the root size during the directory scanner, instead rely on the directory `array_sum` like any other path.
Fixes #930
=> Fix an issue that caused the site size to report as twice as large as it should

backupwordpress.php, classes/class-plugin.php, grunt/aliases.yml, languages/backupwordpress.pot, package.json, readme.txt, readme/readme-footer.txt, readme/readme-header.txt
Bump our version numbers ready for release.
Adds the changelog and an update notice noting WordPress 4.4 compatibility.
Also fixes a minor issue with the build command where the version number in the `.pot` file would be the old version.
=> 3 3 4 release

admin/schedule-sentence.php
Fixes https://github.com/humanmade/backupwordpress/issues/956
=> Strip empty services from the schedule sentence.

classes/class-requirement.php, functions/interface.php
This fixes a PHP Warning when `shell_exec` is disabled.
Instead of using `shell_exec` to find the PHP User and Group we now just show placeholders in the error message. The eventual plan will be to replace these error message with something better (see https://github.com/humanmade/backupwordpress/pull/833)
Also corrects the name of `Exec` requirements check, it was incorrectly mentioning Shell Exec.
Fixes https://github.com/humanmade/backupwordpress/issues/965
=> Stop using shell_exec in warning messages.

classes/class-requirement.php, functions/interface.php
We should potentially look at bringin back a non-PDO mysqldump fallback for users without the above.
Fixes #959
=> Show a warning message if neither mysqldump nor PDO are available

classes/class-path.php, functions/interface.php, tests/misc/test-path-in-open-basedir.php
Check for the existance of `open_basedir` restrictions and ensure we're not accessing paths that fall outside of them.
Removes the need for some error silencing.
I also took the opportunity to improve the error message shown to users who have a restricted custom path.
Fixes https://github.com/humanmade/backupwordpress/issues/964
=> Improved handling of open_basedir restrictions

classes/backup/class-backup.php, classes/class-path.php, tests/class-site-backup/test-class-site-backup.php, tests/test-backup-path.php
There were several issues contributing to this bug.
1. We weren't even running `Path::cleanup` before and after running a backup, we now are.
2. We were missing a unit test to verify that when backing up the database, no other files are included. We now have a unit test.
3. We were missing unit tests for `Path::cleanup` to ensure that all the files we'd expect to are actually cleaned up. We now have unit tests.
4. Those tests exposed the fact that `Path::cleanup` wasn't cleaning up `ZipArchive` temporary files. It now does.
5. `PATH::reset_path` wasn't correctly resetting the `Path::custom_path` meaning that `PATH::cleanup` wouldn't run in some situations. That's now fixed.
So in summary, before this commit temporary files from failed backups were not correctly deleted. After this commit …
=> Ensure temporary files are correctly cleaned up before and after running a backup

classes/backup/class-backup-utilities.php, tests/class-backup-utilities/test-exec-available.php
=> Use preg_split to accomodate multiple delimiters

classes/class-requirement.php
Drop the requirement check for `DirectoryIterator::Follow_Symlinks` as it's no longer used since we switched to Finder.
Also some WPCS fixes.
=> Requirements cleanup

classes/backup/class-backup-engine-database-mysqldump.php
it's only useful when paired with the `--database` or `--all-databases flags`
=> Remove the no-create-db flag

admin/actions.php, admin/schedule-form.php, classes/backup/class-backup.php, classes/class-path.php, classes/class-site-size.php, functions/core.php, tests/test-site-size.php, uninstall.php
Instead of storing an array of all files and their associated filesizes in the DB in a transient we now store it in a hidden `.files` file.
The array of data is `json_encoded` into a string and then compressed with `gzcompress` this helps keep filesizes down.
Adds a unit test to ensure the file is only cached for a week.
=> Switch to storing site size data in a file

uninstall.php
fixes #1018 
Potentially would still fatal error on a PHP 5.2 site that runs uninstall because of the use of namespace?
=> Fix fatal error on uninstall

admin/schedule-form-excludes.php, classes/class-scheduled-backup.php, functions/core.php, functions/interface.php, tests/test-is-same-size-format.php
- The list of files and folders is now ordered by the included filesize, that is the total filesize minus any excludes
- We now display the included filesize for directories in the format "Included size of total size".
- All cells in the table are now wrapped in `<code>` tags
- Unreadable files now show `-` for size and permissions to indicate that we don't actually have the data
Here's how that looks:
=> Improve how filesizes are handled in the Your Site list

bin/release.sh, grunt/concat.js
This script is adapted from the WP API repo.
Once a new version has been tagged and released on github, running `./release.sh {tag}` will download a copy and sync with svn.
It also takes care of deleting unneeded build files before uploading to wp.org
first run `svn list http://plugins.wordpress.org` to accept the certificate
then run `bin/./release.sh {tag}` from the plugin root folder
This will render the `grunt release` step unnecessary, as well as creating the tag release manually.
=> Add release script (WIP)

uninstall.php
Use `get_existing_path` rather than calling `get_path` directly so that we avoid
calling code which relies on `HMBKP_SECURE_KEY`.
Fixes https://github.com/humanmade/backupwordpress/issues/1021
=> Fix a notice on Uninstall and ensure all options are removed

admin/actions.php
Backdrop stops tasks from running more than once every 10 minutes, but it
doesn't clean up the lock if the task ends unexpectedly. So we manually cancel the task
before scheduling.
=> Cancel the backdrop task before scheduling a new one

functions/core.php, functions/interface.php
- Add checks for `mysqldump`/`PDO` as well as `zip`/`ZipArchive` to `hmbkp_possible`. This blocks usage of the plugin if no backup engines are supported.
- Show an error message if there's no zip methods.
- No need to output the dismiss button html as it's inserted automatically.
- Server errors shouldn't be dismissible as they persist until they're fixed.
Fixes https://github.com/humanmade/backupwordpress/issues/935
=> Improve error handling when there's no backup methods supported

assets/hmbkp.js, classes/class-notices.php, tests/test-notices.php
This PR fixes up a bunch of issues in the Notices class and adds full unit test coverage. Issues resolved:
* `(array) get_option` returned an array with a single empty element rather than an empty array.
* Setting a persistent notice duplicated it as it was then in `$this->notices` and the database.
* Calling `get_notices` with a context which didn't exist returned all notices rather than none.
* Calling `set_notices` multiple times with same context overwrote all but the last messages.
* It was possible to set broken messages with empty context or message.
* `update_option` was needlessly called when setting a message that had already previously been set.
It also completes the docblocks and brings the Singleton pattern inline with Path.
=> Add unit tests for the Notices class and fix bugs

functions/interface.php
- Correct check for is_site_size_cached to ensure we only continue if it is cached.
- Check the return value of disk_free_space to ensure it's valid.
Fixes https://github.com/humanmade/backupwordpress/issues/1050
=> Corrects logic and improves error conditions in disk_low_space

admin/schedule-form-excludes.php, tests/class-backup-engine/common-file-backup-engine-tests.php
Fixes #1058 issues with excludes filesizes showing incorrectly.
=> Stop running filesizes through size_format twice.

classes/backup/class-backup-engine-database-mysqldump.php, tests/class-backup-engine/test-class-backup-engine-database-mysqldump.php
The error will be captured in mysqldump anyway and using mysql is an imperfect test which opens the door to false negatives.
=> Stop testing the mysql connection directly

grunt/excludes
=> Exclude codecov.yml from the final plugin build for WP org

admin/extensions.php
=> Extension version text on Extensions page

functions/core.php
Stops low disk space blocking users from accessing BWP settings.
Fixes https://github.com/humanmade/backupwordpress/issues/1131
=> Remove disk_space_low check from is_backup_possible

admin/page.php, admin/schedule-settings.php, functions/interface.php
Remove the check around the admin interface that blocks access if a backup isn't possible. Apply the check instead to the button for triggering a manual backup.
Addresses https://github.com/humanmade/backupwordpress/issues/1030
=> #1030 Remove admin block

functions/interface.php
Pass `Excludes` when calculating the site size in `disk_space_low()` function to give a more accurate response.
Previously, `disk_space_low()` would return true if the entire site (including previous backups) was too big to be backed up, not just the files specified to be backed up.
Addresses https://github.com/humanmade/backupwordpress/issues/1063
=> #1063 Account for excludes when calculating if disk space is too low

admin/menu.php
Forces the main BWP 'Backups' page to be highlighted in the admin sidebar when visiting the 'Extensions' page. 
Achieved by setting the main 'Backups' page to be the current subpage when on the 'Extensions' page via the `parent_file` hook.
Addresses #1125.
=> #1125 Highlight the 'Backups' submenu item when on the Extentions page

classes/class-notices.php
Previously, any new admin notices were merged into the array of persistent notices in the database without checking if the new notice already existed as a persistent notice, causing the database to fill up with multiple instances of the same message. This wasn't seen in the admin because array_unique is used before outputting each notice.
=> Ensure only new persistant notices are added added to the database

classes/class-excludes.php
This wildcard set is causing wp-snapshots to NOT be excluded per report from user in forum. I confirmed this on my test site, and changed the plugin back to the previous iteration which was just using 'wp-snapshots' - and that worked perfectly. Unsure exactly why this happened but pretty sure the wildcard specification needs further translating for regex to do it correctly?
=> Fix wp-snapshots

admin/page.php, admin/upsell.php, classes/class-plugin.php
This changes the extension links in three places to link back to the website instead of to the extensions page. Per meeting and workshop with Products team, we want to focus on improving the funnel onsite before we re-integrate the extensions page onsite and work on purchasing ability from there. 
Should the actual extensions page be pulled out to it's own PR, ie. removed from current code and re-added via a PR so we can work on completing the full extension page updates and potentially adding in purchase links? Let's ask @pdewouters for feedback here if he has a moment? 
As for reviewing the commits - I'm still shaky on when to escape and whether I did that correctly, so would like to have conversation regarding that ;-)
=> Change extension links for BWP
