admin/actions.php
- Only re-run the test once per week, unless it fails.
- Fire 3 remote requests and only show a warning if each of them errors, this should help avoid one off issues, see #557
=> Improve the reliability of the wp-cron test

classes/class-hmbkp-path.php, functions/interface.php
***DO NOT MERGE***
So we can test for these kinds of errors `backup error - open_basedir restriction in effect`
Context https://github.com/humanmade/backupwordpress/issues/246
=> Unit tests for open base dir

backupwordpress.php, classes/class-backup.php, classes/class-schedule.php, functions/core.php
We can pass the date format as a param to `current_time`
=> Simplify bwp file timestamp name creation

classes/class-backupwordpress-wp-cli-command.php
Reported in https://github.com/wp-cli/wp-cli/issues/1635
=> Fix class name

admin/actions.php, admin/enable-support.php, admin/schedule-settings.php, classes/class-backup.php
There's a PR ready to go on the old HM-Backup repo: https://github.com/humanmade/hm-backup/pull/72
=> Add support for socket path in hostname field

classes/class-backup.php
user reported this. maybe because we ex
=> backup missing cache.php file from wp-inclides directory

CONTRIBUTING.md
Assigned to @pdewouters.
I am also wondering if it might be benefical to mention what branch the contributor should PR against. There is no dev, so master seems to be the obvious choice.
=> Added colons and several periods

classes/class-setup.php, tests/bootstrap.php, tests/other/testUninstallActivateDeactivate.php
Not sure the tests are correct because if I comment out the calls to `register_activation_hook` and `register_deactivation_hook`, the tests still pass. Although if I comment out the line `deactivate_plugin` in the deactivation test, it fails...
@johnbillion @willmot thoughts?
=> Fix activation

classes/class-backupwordpress-wp-cli-command.php
=> Use namespaced functions II

admin/actions.php, admin/enable-support.php, admin/faq.php, admin/schedule-form.php, backupwordpress.php, classes/class-backup.php, classes/class-email-service.php, classes/class-plugin.php, classes/class-schedule.php, functions/core.php, functions/interface.php, readme.txt, readme/readme-header.txt
=> grammar, punctuation, etc.

classes/class-schedule.php, classes/class-service.php
Started off as a fix for vulnerabilities reported by Scrutinizer, but after reading the code, it is already handlind the sanitizing correctly. So false positive
=> Fixes some function docs and use different sanitizing function

.scrutinizer.yml
Add WP coding standards
Disable redundant checks
=> Update Scrutinizer conf

.travis.yml
As we are using git and checking out master, we need to check for "master"
=> Fix conditional value

admin/actions.php, grunt/excludes
- Fix broken download URL due to missing trailing slash 
- Also exclude phpunit config from build
=> Fix download url

classes/class-schedule.php
Fixes https://github.com/humanmade/backupwordpress/issues/812
=> Make sure we return an int

.scrutinizer.yml, .travis.yml
I've thing codecov gives us better a better unit test coverage browser than scrutiniser.
=> Switch to using codecov for code coverage

admin/constants.php, admin/faq.php, classes/class-email-service.php, classes/class-schedule.php, functions/interface.php
Hi,
I just translated the plugin at translate.wordpress.org and found a few typos.
=> Fixes Typos

admin/page.php
After you enable support, the support modal is now broken.
=> Support modal broken

functions/core.php
- Fix a fatal error in the upgrade routine
- Ensure old backups are correctly renamed so that the legacy schedule recognises them
- Ensure that the default schedules run after the upgrade routine so that they aren't added if there's already a legacy schedule
Fixes https://github.com/humanmade/backupwordpress/issues/972
=> Ensure backups and schedules are properly migrated from pre-2.0

classes/class-path.php, tests/class-backup-utilities/test-get-home-path.php
=> Detect subdir install by comparing home url and site url

classes/class-path.php, tests/class-backup-utilities/test-get-home-path.php
I extracted the code from the core function `get_home_path` to use in our `get_home_path()` function
Should fix https://github.com/humanmade/backupwordpress/issues/976
=> Takes logic from core get_home_path

backupwordpress.php, classes/class-plugin.php, classes/class-setup.php
=> Avoid killing site if plugin is active on PHP 52

classes/class-plugin.php
Sometimes it could be useful to allow custom secure key. I added simple filter for that.
=> Allow custom secure key using filter

admin/schedule-form-excludes.php
Bunch of coding standards fixes
=> Only call getPerms on readable files to ensure we avoid a fatal error

classes/backup/class-backup.php
=> Add back compat function

classes/class-path.php
Fixes root path issues on Windows
=> Normalize paths before working with them

classes/class-backupwordpress-wp-cli-command.php
Fixes #1009 
@willmot or @duritong - want to test this fix?
=> Fix excludes error

classes/backup/class-backup-engine-database-mysqldump.php, classes/backup/class-backup-utilities.php, classes/class-requirement.php, tests/class-backup-utilities/test-get-executable-path.php
Fixes https://github.com/humanmade/backupwordpress/issues/1049
=> Check for proc_close as well as proc_open

admin/schedule-form-excludes.php
@willmot while we're here - fix minor Coding Standards issues. Align code for better readability.
=> Fix coding standards (while working on 1058)

.gitmodules, classes/class-plugin.php
=> Add Whitelist HTML submodule and load it for use in the plugin

admin/actions.php, classes/class-scheduled-backup.php, classes/class-schedules.php, classes/class-site-size.php
Some attempts to reduce the impact BackUpWordPress has on admin performance.
=> Admin performance improvements

codecov.yml
=> New settings file for codecov

admin/schedule-sentence.php
Fixes https://github.com/humanmade/backupwordpress/issues/1099
=> Hide site size until it's calculated

classes/class-excludes.php
=> 1105 default excludes

readme.txt
=> Add katmoody to the list of contributors

.scrutinizer.yml, admin/actions.php, admin/schedule-form.php, admin/schedule-sentence.php, assets/hmbkp.js, classes/backup/class-backup-engine-database-mysqldump.php, classes/backup/class-backup-engine-database.php, classes/backup/class-backup-engine-file-zip.php, classes/backup/class-backup-engine-file.php, classes/backup/class-backup-engine.php, classes/backup/class-backup-status.php, classes/backup/class-backup.php, classes/class-email-service.php, classes/class-path.php, classes/class-requirement.php, classes/class-requirements.php
Fix a bunch of minor issues raised by Scrutinizer.
See https://github.com/humanmade/backupwordpress/issues/1031
=> Scrutinizer fixes

CONTRIBUTING.md, admin/faq.php, admin/page.php, backupwordpress.php, classes/class-email-service.php, classes/class-plugin.php, classes/class-setup.php, functions/interface.php, grunt/makepot.js, readme.md, readme.txt, readme/readme-footer.txt, readme/readme-header.txt
Email and old website changes.
XIBO ownership changes
=> Description link updates

admin/actions.php, admin/upsell.php, assets/hmbkp.js, classes/class-plugin.php
Fixes the admin notice dismissal. The notice asking for a rating will display every 30 days.
=> Fix admin notices

classes/class-extensions.php, classes/class-notices.php, classes/class-path.php, classes/class-plugin.php
=> PHP 8.0 compatibility
